Module.SPV_BINARY_TO_TEXT_OPTION_NONE = 1;
Module.SPV_BINARY_TO_TEXT_OPTION_PRINT = 2;
Module.SPV_BINARY_TO_TEXT_OPTION_COLOR = 4;
Module.SPV_BINARY_TO_TEXT_OPTION_INDENT = 8;
Module.SPV_BINARY_TO_TEXT_OPTION_SHOW_BYTE_OFFSET = 16;
Module.SPV_BINARY_TO_TEXT_OPTION_NO_HEADER = 32;
Module.SPV_BINARY_TO_TEXT_OPTION_FRIENDLY_NAMES = 64;
