name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build the Docker image
        run: docker-compose build
      - name: Build web
        run: docker-compose run --rm build ./build.sh
      - name: Run tests
        run: node test/test.js
      - name: Publish to npm
        uses: primer/publish@v2.0.0
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
